#!/usr/bin/env node
// pnpm db:sync [--check] [--quiet]
// Regenerates every database artifact from supabase/migrations WITHOUT a running database:
// the migrations are applied to an in-memory Postgres (PGlite, see lib/offline-db.mjs).
//   db/schema/master-schema.sql               master schema (pg_dump of the application schemas)
//   db/schema/schema.dbml                     engine-neutral model
//   db/schema/portable/*.sql                  starting-point DDL for MySQL, SQL Server, SQLite
//   db/export/queries/*.sql                   portable per-table export queries (FK load order)
//   db/export/manifest.json                   load order, columns and type mapping
//   db/portability/supabase-dependencies.md   Supabase-specific constructs in use
//   src/types/database.types.ts               TypeScript types (when src/ exists)
//   db/schema/.migrations-hash                fingerprint used by hooks and CI to detect stale artifacts
// It also validates the migrations (a failing migration stops with file and line) and seed.sql.
// Options:
//   --check   regenerate, then fail if any artifact differs from the committed version (CI)
//   --quiet   print only problems (used by the harness hook after a migration is written)
// Owner: database-architect.
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const args = new Set(process.argv.slice(2));
const CHECK = args.has('--check');
const QUIET = args.has('--quiet');
const log = (msg) => {
  if (!QUIET) console.log(msg);
};

const lib = (p) => import(pathToFileURL(path.join(ROOT, p)).href);

function write(rel, content) {
  const abs = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  const before = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (before !== content) fs.writeFileSync(abs, content, 'utf8');
}

function formatTypes(rel) {
  const prettier = path.join(ROOT, 'node_modules', '.bin', 'prettier');
  if (fs.existsSync(prettier)) spawnSync(prettier, ['--write', '--log-level', 'warn', rel], { cwd: ROOT, stdio: 'ignore' });
}

async function main() {
  const { buildDatabase, runnerFor, dumpSchema, generateTypes, applySeed } = await lib('scripts/db/lib/offline-db.mjs');
  const { generate, MANAGED_SCHEMAS } = await lib('scripts/db/lib/generate-artifacts.mjs');

  const started = Date.now();
  const { db, migrations, notes, version } = await buildDatabase(ROOT);
  try {
    log(`db:sync: applied ${migrations.length} migrations to an in-memory Postgres ${version} (no Docker, no remote database)`);

    const dump = await dumpSchema(db, ROOT, MANAGED_SCHEMAS);
    write(
      'db/schema/master-schema.sql',
      [
        '-- GENERATED by pnpm db:sync from supabase/migrations. Do not edit.',
        '-- Master schema: current definition of every application schema (Supabase platform schemas excluded).',
        '-- Recreate on any Postgres with: psql -f db/schema/master-schema.sql (after creating the roles it grants to).',
        '',
        dump.trim(),
        '',
      ].join('\n'),
    );

    const res = await generate({ root: ROOT, query: runnerFor(db) });
    log(`db:sync: ${res.tables} tables exported${res.cycles.length ? ` (FK cycles broken at: ${res.cycles.join(', ')})` : ''}, ${res.dependencies} Supabase-specific constructs inventoried`);

    if (fs.existsSync(path.join(ROOT, 'src'))) {
      const types = await generateTypes(db, ROOT, ['public']);
      write('src/types/database.types.ts', types);
      formatTypes('src/types/database.types.ts');
      log('db:sync: TypeScript types written to src/types/database.types.ts');
    }

    const seedError = await applySeed(db, ROOT);
    if (seedError) console.warn(`db:sync: warning: seed does not apply offline: ${seedError}`);
    for (const n of notes) console.warn(`db:sync: note: ${n}`);
  } finally {
    await db.close();
  }

  const { migrationsFingerprint, HASH_FILE } = await lib('.claude/harness/lib/db.mjs');
  write(HASH_FILE, `${migrationsFingerprint(ROOT).hash}\n`);
  log(`db:sync: done in ${((Date.now() - started) / 1000).toFixed(1)}s`);

  const paths = ['db', 'src/types/database.types.ts'].filter((p) => fs.existsSync(path.join(ROOT, p)));
  const status = spawnSync('git', ['status', '--porcelain', '--', ...paths], { cwd: ROOT, encoding: 'utf8' });
  const changed = (status.stdout || '').trim();
  if (CHECK) {
    if (changed) {
      console.error('db:check: generated database artifacts differ from the committed ones:');
      console.error(changed);
      console.error('Run pnpm db:sync and commit db/ and src/types/database.types.ts with the migration.');
      process.exit(1);
    }
    log('db:check: artifacts match supabase/migrations');
  } else if (changed) {
    log('db:sync: commit these files together with the migration:');
    log(changed);
  }
}

main().catch((err) => {
  console.error(`db:sync failed: ${err.message}`);
  process.exit(1);
});
